version: '3'

services:
  server:
    ports: 
      - "9999:9999"
    build: .
    depends_on:
      - "database"
    command: yarn prepare-environment-docker
  database:
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes: 
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      PGPASSWORD: "123456"